name: demo
run-name: ${{ github.actor }} is running the demo
on:
  workflow_dispatch:
jobs:
  demo:
    runs-on: self-hosted
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.
      - name: Make the executable 
        run: make
      - name: Run a demo from the folder
        run: echo running; ./myFind
