name: compile and run project
run-name: ${{ github.actor }} is running the project
on: [push]
jobs:
  make:
    runs-on: self-hosted
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.
      - name: Make the executable 
        run: make
      - name: Run a demo from the folder
        run: ./myFind
